### PR TITLE
deallocate rmw_init_options.enclave in rmw implementaion.

### LINKED ISSUE #311: Memory leak from enclave
**Describe the bug**
Context https://github.com/ros2/rcl/issues/1198 and https://github.com/Yaskawa-Global/motoros2/issues/35

I believe that there is a possible memory leak in rmw_microxrcedds. In the micro-ROS rcl repo, the following lines duplicate a string and dynamically allocate the memory if `RCL_MICROROS_COMPLETE_IMPL` is set.

https://github.com/micro-ROS/rcl/blob/041a67a2e102e9c48ae2580f19b2677016fcf86a/rcl/src/rcl/init.c#L265-L273

This memory which is dynamically allocated for `enclave` via `rcutils_strdup` is deallocated in other (full) rmw implementations. For example:

https://github.com/ros2/rmw_fastrtps/blob/1128b57d336dfa8bf462a5f9147291f73faa8ed3/rmw_fastrtps_shared_cpp/src/rmw_init.cpp#L116

However it is never deallocated in rmw_microxrcedds. I believe that this is only a problem if `RCL_MICROROS_COMPLETE_IMPL` is set, because that is the only case where `rcutils_strdup` runs and sets aside dynamic memory. 

I do not believe that the solution is as simple as freeing the memory in `rmw_init_options_fini`, because the code below copies the `enclave` data to static memory, and thus cannot be freed. I might be wrong about that. 

https://github.com/micro-ROS/rcl/blob/041a67a2e102e9c48ae2580f19b2677016fcf86a/rcl/src/rcl/init.c#L105-L110

**To Reproduce**
~~I do not have a MWE, but it is apparent in [MotoROS2](https://github.com/Yaskawa-Global/motoros2) using the debug listener script.~~ edit - I have a MWE below

**Expected behaviour**
I expect the memory set aside by `rcutils_strdup` to be freed by the rmw, as it is with other rmws. 

**System information (please complete the following information):**
 - YRC1000 
 - ROS 2: I am currently using Jazzy. I believe that the problem exists on Humble as well, though. 
 - Version: I am currently using a fork off of 2.4.3

Please let me know if I need to provide any more information, or if I am doing something improperly. Thank you.

### PR DESCRIPTION
**Pull request by fujitatomoya**
closes https://github.com/micro-ROS/rmw_microxrcedds/issues/311

this is jazzy fix of https://github.com/micro-ROS/rmw_microxrcedds/pull/318, should be backported to humble as well.

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
CC: @pablogs9 @jimmy-mcelwain

**Comment by jimmy-mcelwain** [comment]
I don't know this repo particularly well and maybe the PR will need to change because of the failing CI, but I rebuilt MotoROS2 with this PR included on the YRC1000, and the memory leak seems to be gone!

**Comment by fujitatomoya** [comment]
@jimmy-mcelwain thanks for checking 👍 

CI tells `implicit declaration of function ‘rcutils_strdup’ [-Werror=implicit-function-declaration]`, i will patch it.

**Comment by fujitatomoya** [comment]
@pablogs9 this is CI green.

File: rmw_microxrcedds_c/src/rmw_init.c [hunk 1]
```diff
@@ -135,8 +137,16 @@ rmw_init_options_copy(
   }
   memcpy(dst, src, sizeof(rmw_init_options_t));
 
+  rcutils_allocator_t allocator = src->allocator;
+  RCUTILS_CHECK_ALLOCATOR(&allocator, return RMW_RET_INVALID_ARGUMENT);
+  dst->enclave = rcutils_strdup(src->enclave, allocator);
```
Comment (pablogs9) [inline rmw_microxrcedds_c/src/rmw_init.c:142]: Shall this be conditioned to src->enclave being not NULL?

Comment (pablogs9) [reply rmw_microxrcedds_c/src/rmw_init.c:142]: I've checked that it returns NULL

**Review by pablogs9 — APPROVED** [review]

**Comment by fujitatomoya** [comment]
@pablogs9 thanks for the review, and merging!

**Comment by fujitatomoya** [comment]
@Mergifyio backport humble

**Comment by pablogs9** [comment]
@mergify backport humble
